# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CBC_LU_RockCreekWS.py
# Created on: 2018-05-16 15:06:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
DC_11001_WGS1984_img = "DC_11001_WGS1984.img"
DC_LC_Proj = "D:\\RockCreekPark\\Data\\Rasters\\DC_LC_Proj"
CBCLU_DC_Poly_shp = "D:\\RockCreekPark\\Data\\Shapefiles\\CBCLandUse\\CBCLU_DC_Poly.shp"
RockCreek_PotomacRiver_Watershed = "RockCreek_PotomacRiver_Watershed"
CBCLU_DC_RockCreekPotomacWS_shp = "D:\\RockCreekPark\\Data\\Shapefiles\\CBCLandUse\\CBCLU_DC_RockCreekPotomacWS.shp"

# Set Geoprocessing environments
arcpy.env.autoCommit = "1000"
arcpy.env.cartographicPartitions = ""
arcpy.env.compression = "LZ77"
arcpy.env.rasterStatistics = "STATISTICS 1 1"
arcpy.env.transferDomains = "false"
arcpy.env.maintainAttachments = "true"
arcpy.env.resamplingMethod = "NEAREST"
arcpy.env.cartographicCoordinateSystem = ""
arcpy.env.configKeyword = ""
arcpy.env.qualifiedFieldNames = "true"
arcpy.env.tileSize = "128 128"
arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
arcpy.env.referenceScale = ""
arcpy.env.nodata = "NONE"
arcpy.env.cellSize = "MAXOF"
arcpy.env.mask = ""

# Process: Project Raster
arcpy.ProjectRaster_management(DC_11001_WGS1984_img, DC_LC_Proj, "PROJCS['NAD_1983_StatePlane_Maryland_FIPS_1900',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',400000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-77.0],PARAMETER['Standard_Parallel_1',38.3],PARAMETER['Standard_Parallel_2',39.45],PARAMETER['Latitude_Of_Origin',37.66666666666666],UNIT['Meter',1.0]]", "NEAREST", "1.18236705408999 1.18236705408997", "WGS_1984_(ITRF00)_To_NAD_1983", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(DC_LC_Proj, CBCLU_DC_Poly_shp, "SIMPLIFY", "", "SINGLE_OUTER_PART", "")

# Process: Clip
arcpy.Clip_analysis(CBCLU_DC_Poly_shp, RockCreek_PotomacRiver_Watershed, CBCLU_DC_RockCreekPotomacWS_shp, "")

