# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Pivot.py
# Created on: 2018-05-18 11:31:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
v2018_Watering_Trees = "2018 Watering Trees"
Test_Pivot_2_csv = "D:\\WateringMaps\\Models\\Excel_Outputs\\Test_Pivot_2.csv"

# Process: Pivot Table
arcpy.PivotTable_management(v2018_Watering_Trees, "Location", "Year", "Jurisdictn", Test_Pivot_2_csv)

