# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Select_CopyRows.py
# Created on: 2018-05-17 14:14:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
v2018_Watering_Trees_Append = "2018_Watering_Trees_Append"
test_1_shp = "D:\\WateringMaps\\Models\\OFCs\\test_1.shp"
test_1_AoH_csv = "D:\\WateringMaps\\Models\\Excel_Outputs\\test_1_AoH.csv"

# Process: Select
arcpy.Select_analysis(v2018_Watering_Trees_Append, test_1_shp, "\"Location\" = 'Academy of Hope PCS'")

# Process: Copy Rows
arcpy.CopyRows_management(test_1_shp, test_1_AoH_csv, "")

